app = 'react-application-template'
primary_region = 'arn'

[env]
  PORT = '9000'

[[services]]
  internal_port = 9000
  protocol = 'tcp'
  min_machines_running = 1

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ['http']
    port = 80

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

  [[services.tcp_checks]]
    grace_period = '30s'
    interval = '15s'
    timeout = '2s'
    restart_limit = 0
